version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - vuelibs-net
    environment:
      - LOGDNA_KEY: ${LOGDNA_KEY}
      - OCTOKIT_TOKEN: ${OCTOKIT_TOKEN}
      - ENV: prod
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - vuelibs-net

networks:
  vuelibs-net:
    driver: bridge
